[package]
name = "winamp-native"
version = "0.1.0"
edition = "2024"

[dependencies]
audio = { version = "0.1.0", path = "../../crates/audio" }
cpal = "0.18"
crossterm = "0.29.0"
eframe = { version = "0.36", default-features = false, features = ["wgpu", "default_fonts"] }
platform = { version = "0.1.0", path = "../../crates/platform" }
ui = { version = "0.1.0", path = "../../crates/ui" }
