[package]
name = "audio"
version = "0.1.0"
edition = "2024"

[dependencies]
audioadapter-buffers = "5"
platform = { version = "0.1.0", path = "../platform" }
ron = "0.12.2"
rtrb = "0.4.0"
rubato = "5.0.0"
serde = { version = "1.0.229", features = ["derive"] }
symphonia = { version = "0.6.1", features = ["all"] }
thiserror = "2.0.21"

[dev-dependencies]
hound = "3.5.1"
rtrb = "0.4"
